---
title: "Arbeidskrav_5_Studiedesign"
format: html
editor: visual
---

## Arbeidskrav 5 - Studiedesign


I dette arbeidskravet skal jeg se på fem ulike studier som ser på sammenhengen av styrketrening og dens effekt på running efficiency (RE). Vi skal se litt på hvordan de ulike studiene er gjennomført, hva fellesnevner er for dem og hva de gjør annerledes fra hverandre.

# Hypotesene
Skal man først se de ulike studiene bør man jo først finne ut av hva slags hypotese eller problemstilling det er de har prøvd og finne svaret på. Ser vi på hva Turner et al. , (2003) sitt studiet så har de en enkel hypotese som er: En 6 ukers treningsperiode hvor en middels trent utholdenhets utholdenhetsutøver trener både styrke og utholdenhet vil se en bedring av utøverens RE. Saunders et al.  (2006) har en lignende hypotese bare da er fokus på hva de kaller normal trente eliteutøvere,  altså utholdenhetsutøvere som kun har fokusert på utholdenhetstrening med liten eller ingen erfaring innenfor styrketrening. 

Søren et al. (2008) sitt studiet derimot fokuserer seg mer inn på en enkelt øvelse og om den har en effekt på RE og hypotesen dems lyder slik: “MST (maximal strength training) utført som half squats og et supplement til utholdenhetstrening vil øke 1rm, rfd, RE og tid til total utmattelse ved maksimal aerob hastighet (MAS).” Her ser de også da på om MST har en effekt på flere områder enn kun på RE.

Guglielmo et al. (2009) skiller seg litt ut fra de andre studiene jeg har valgt ved at istedenfor å kun se på om maksimal styrketrening har effekt på RE så ser de også på om maksimal styrketrening har en større effekt på RE sammenlignet med eksplosiv styrketrening, men Guglielmo et al. (2009) har ingen ordentlig hypotese annet enn at styrketreningene har en effekt på RE. 
  Millet et al. (2002) sitt studiet baserer seg mer på å observere og så komme med en teori på observasjonene. Årsaken er at som de nevner i studien sin er det mangel på studier som viser en sammenheng mellom tung styrketrening og RE. Derfor kjører de et studie for å se om hva slags observasjoner det er de får ved å gjennomføre studiet deres og om de kan få en bedre forståelse for dette emnet.

Når man ser på hvordan deltakerne på disse studiene ser man at alle studiene har valgt å teste elite/nasjonalt eller internasjonalt konkurrerende utøvere. Unntaket er Turner et al. (2003) som har valgt å rekruttere hva de vil kalle for middels trente utøvere. Årsaken til at studiene ikke har valgt å teste utrente deltakere er fordi at man vet at utrente som regel alltid kommer til å ha en kraftig respons på trening uansett om det er ren utholdenhetstrening eller styrke og utholdenhetstrening. En annen ting som er lurt å nevne er også at utrente personer vil som regel ikke være vant med å løpe som igjen vil si at all utholdenhetstrening de gjør vil bedre arbeidsøkonomien deres siden teknikken til deltakeren blir bedre og det vil gjøre det vanskelig å måle hvor mye av forbedringen av RE kommer fra styrketreningen, utholdenhetstreningen og bedring av teknikk.
 Fordelen med å velge trente deltakere på et så høyt nivå er at det gjør det mye lettere og finne ut av hvor mye av forbedringen i RE kommer fra styrketrening siden man må ha større trening stimuli for å forbedre prestasjonsevnen deres.

En ting som kan være nyttig og nevne er at studien til Saunders et al. (2006) sier at de ser på om styrketrening har en akutt effekt på RE siden de har sett ved et tidligere studiet at kunstig høydetrening har vist en positiv effekt hos eliteutøvere, men grunnet at ikke alle lag og utøvere ikke har tilgang på dette så ser de på om styrketrening kan være en annen treningsmetode på å forbedre RE.

De fem forskjellige studiene brukte lignende studiedesign,  nemlig et studiedesign kalt randomisert kontrollert studie, men noen hadde en liten vri i tillegg. Det som var felles for alle var at de hadde en intervensjonsgruppe og en kontrollgruppe og så var det randomisert hvem som var på hvilken gruppe. Deretter ble det gjort en pre og en posttest på begge gruppene. Det ble gjort noen unntak som i Millet et al.  (2002) sitt studiet hvor de sørget for at de elite deltakerne dem hadde som konkurrerte på internasjonalt nivå ble jevnt fordelt på de to gruppene (3 i intervensjonsgruppen og 4 i kontrollgruppa.) Det samme gjaldt hos Støren et al. (2008) bare at fokuset var og ha kjønnsfordelingen lik. Et annet unntak om det er det man kan kalle det er det at Turner et al. (2003) kjørte en ekstra test etter 1-2 uker at intervensjonen hadde startet i tillegg til pre og post test. 

Årsaken til at studiene har valgt og gjøre et randomisert kontrollert studie er for å sørge for at studiet blir så objektivt som mulig. Ulempen med å kjøre et slikt studie design er jo at man ikke har kontroll over om nivået i hver gruppe blir likt, det er derfor sørget noen av studiene for at det var ca like mange av hvert kjønn på hver gruppe og Millet et al. (2002) et al. (2002) sørget for at elite utøverne var jevnt fordelt.                                               

Saunders et al. (2006) sitt studie følger også studie-designet “repeated-measures design study” som vil si at deltakerne blir testet over en periode, i tillegg til en pre og post test. I dette tilfellet ble deltakerne først testet for å se om de var gode nok til å delta på studiet, som også var en pre-test, når intervensjonen begynte ble deltakerne testet i uke 5 og uke 9 i tillegg til post test.

# Tester
Millet et al. (2002) testen hadde flere forskjellige tester, disse bestod av Maksimal hopp test, 3000m løp på en bestemt fart, en maksimal konsentrasjonstest av beina. De hadde også en “incremental running test” til man ikke klarte mer for å finne VO2max og RE. 
Saunders et al. (2006) sitt studiet målte RE ved å ha utøveren løpe på tre bestemte hastigheter på en tredemølle samtidig som at det ble målt laktat, puls og O2 opptak. Støren et al. (2008) hadde også en lignende protokoll til å te RE, men det blir bare nevnt at deltakerne løper i perioder på 5 min på en gitt stigning på tredemøllen, men med varierende fart. 

Hvis man ser på disse testene så virker det som at de har potensial til å være ganske reliable tester, men ingen av testene nevner hvordan det er de bestemmer farten til deltakerne. Dette skader også validiteten grunnet at det gjør det mer til gjetting for å finne ut av hvor fort hver av dem løp. Man kan jo se på en styrke med disse testene som blir gjort og det er jo at de fleste deltakerne er nok sannsynligvis vandt med å gjennomføre slike tester grunnet at det er ganske høyt nivå på deltakerne gjennom testene og siden dataen blir skjult for dem fra pre til posttest så unngår man til best evne at man presterer bedre på grunn av ren psykologi. Samtidig så vil man unngå at deltakerne presterer bedre grunnet læringskurven som kommer når man blir testet, dette kan være en svakhet derimot ved styrketestene som blir gjennomført, årsaken er at mange av deltakerne har liten til ingen erfaring med styrketrening som da vil kunne ha en effekt på resultatet på testene siden det er en større læringskurve enn hos en løpetest. 


# Statistisk analyser

For å finne ut om observasjonene man har fått egentlig har noe sammenheng og betydning så må man jo analysere dataen man har samlet inn. Hvordan man gjør det varierer jo fra hva slags studiet man kjører og hva det er man leter etter. Alle valgte studier brukte en ANOVA analyse som står for “Analysis of Variance” som er en måte å se på forskjellen mellom to grupper, sånn intervensjonsgruppen og kontrollgruppen. Det var kun et studiet som ikke brukte ANOVA og det var  Støren et al. (2008) sitt studiet.

Istedenfor valgte  Støren et al. (2008) å bruke en paired t-test og en independent t-test. Studiet til Turner et al. (2003) valgte også å kjøre en independent t-test, dette går da ut på å regne ut forskjellen mellom to målinger, i dette tilfelle pre og posttest innad i samme gruppe, men en paired t-test går ut på å regne ut forskjellen mellom kontrollgruppen og intervensjonsgruppen. 

Alle studiene de regnet også ut Effect size (ES) De fremstilte også daten med median, SD (Standard Deviation) og p-value hvor de satte en grense på <0.05
Sammenlignet med de andre så valgte Saunders et al (2006) å ikke bruke p verdi men istedenfor å kun bruke ES hvor de satte kriterier for tolkning, nemlig at en ES verdi på under <0.02 ble ansett på som ubetydelige, <0.6 ble sett på som liten betydning, <1.2 moderat betydning og >1.2 har stor effekt.



# Resultat
Når det kommer til resultatene så kommer alle studiene frem til det samme, og trene maksimal styrketrening har en signifikant effekt på RE hos elite og moderat trente utøvere. 

Hvis vi ser på problemstillingen til Guglielmo et al, (2009) hvor de de ser på hva som gir størst endring i RE av maksimal styrketrening (HWT) og eksplosiv trening (EST) så kommer de frem til at det var en signifikant økning (p < 0.05) i RE hos de som hørte til i gruppen HWT. Her lå snittet på rundt 6,2% bedring i RE sammenlignet med EST som ikke hadde en signifikant økning (p 0.67) og lå rundt 1.9% bedring i RE. Dette gir oss jo da svaret at maksimal styrketrening er mer gunstig for forbedring av RE enn eksplosiv styrketrening.

De andre studiene hjelper med å bygge på dette ved at alle fant en signifikant økning av RE selv om alle hadde fokus på maksimal styrketrening så varierte treningsprogrammene fra studiet til studiet. En annen ting som ble oppdaget var at selv med styrketrening i treningsplanen så ble det ikke oppdaget en signifikant økning innen VO2max eller body mass. 

Så for å oppsummere så så vi på fem ulike studier som tok for seg sammenhengen mellom styrketrening og dens effekt på løpsøkonomien i både moderat trente og eliteutøvere.  Selv om de hadde ulike protokoller så kom alle frem til at styrketrening spesielt tung har en gunstig effekt på RE og vil være en anbefaling til alle utøvere som ønsker å bli bedre.



# Kilder
Guglielmo, L. G. A., Greco, C. C., & Denadai, B. S. (2009). Effects of Strength Training on Running Economy. International Journal of Sports Medicine, 30(1), 27–32. https://doi.org/10.1055/s-2008-1038792

Millet, G. P., Jaouen, B., Borrani, F., & Candau, R. (2002). Effects of concurrent endurance and strength training on running economy and V̇O2 kinetics. Medicine & Science in Sports & Exercise, 34(8), 1351.

Saunders, P. U., Telford, R. D., Pyne, D. B., Peltola, E. M., Cunningham, R. B., Gore, C. J., & Hawley, J. A. (2006). SHORT-TERM PLYOMETRIC TRAINING IMPROVES RUNNING ECONOMY IN HIGHLY TRAINED MIDDLE AND LONG DISTANCE RUNNERS. The Journal of Strength & Conditioning Research, 20(4), 947.

Støren, Ø., Helgerud, J., Støa, E. M., & Hoff, J. (2008). Maximal Strength Training Improves Running Economy in Distance Runners. Medicine & Science in Sports & Exercise, 40(6), 1087. https://doi.org/10.1249/MSS.0b013e318168da2f

Turner, A. M., Owings, M., & Schwane, J. A. (2003). Improvement in Running Economy After 6 Weeks of Plyometric Training. The Journal of Strength & Conditioning Research, 17(1), 60.
